language: python
python:
  - "2.7"
install:
  - pip install .
  - pip install coveralls
  - pip install numpy
  - pip install pytest
  - pip install twisted
before_script:
  - wget https://bintray.com/artifact/download/maffoo/generic/scalabrad-0.2-SNAPSHOT.tar.gz -O /tmp/scalabrad-0.2-SNAPSHOT.tar.gz
  - tar -xvf /tmp/scalabrad-0.2-SNAPSHOT.tar.gz
  - export PATH=$PATH:$PWD/scalabrad-0.2-SNAPSHOT/bin/
script: scripts/test/test.sh
after_success:
  - coveralls
