#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Labrad/Google/gwt/gwt-user.jar:/Labrad/Google/gwt/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.labrad.NodeController/NodeController.html;
