#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/Library/Google/gwt/gwt-user.jar:/Library/Google/gwt/gwt-dev-mac.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/../pylabrad/labrad/controller/gwt/www" "$@" org.labrad.NodeController;
