#!/bin/sh

### BEGIN INIT INFO
# Provides: labradcontrol
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Provides a web interface for controlling a LabRAD network.
# Description: Provides a web interface for controlling a LabRAD network.
### END INIT INFO

## Environment Variables
#export PYTHONPATH=
#export LABRADHOST=localhost
#export LABRADPORT=7682
#export LABRADNODE=
#export LABRADPASSWORD=

LOGDIR=/var/log/labrad
RUNDIR=/var/run/labrad
LOGFILE=control.log
PIDFILE=control.pid
CMD=labradcontrol

case "$1" in
    'start')
        echo "Starting labradcontrol..."
        mkdir $LOGDIR
        mkdir $RUNDIR
        twistd --pidfile $RUNDIR/$PIDFILE --logfile $LOGDIR/$LOGFILE $CMD
        ;;
        
    'stop')
        echo "Stopping labradcontrol..."
        kill `cat $RUNDIR/$PIDFILE`
        ;;
        
    'restart')
        $0 stop
        $0 start
        ;;
        
    *)
        echo "Usage: $0 { start | stop }"
        ;;
esac

# TODO: add status, try-restart, reload, force-reload

exit 0