#!/bin/sh

### BEGIN INIT INFO
# Provides: labradcontrol
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Allows to start and stop servers in a LabRAD network.
# Description: Allows to start and stop servers in a LabRAD network.
### END INIT INFO

## Environment Variables
#export PYTHONPATH=
#export LABRADHOST=localhost
#export LABRADPORT=7682
#export LABRADNODE=
#export LABRADPASSWORD=

LOGDIR=/var/log/labrad
RUNDIR=/var/run/labrad
LOGFILE=node.log
PIDFILE=node.pid
CMD=labradnode

case "$1" in
    'start')
        echo "Starting labradnode..."
        mkdir $LOGDIR
        mkdir $RUNDIR
        twistd --pidfile $RUNDIR/$PIDFILE --logfile $LOGDIR/$LOGFILE $CMD
        ;;
        
    'stop')
        echo "Stopping labradnode..."
        kill `cat $RUNDIR/$PIDFILE`
        ;;
        
    'restart')
        $0 stop
        $0 start
        ;;
        
    *)
        echo "Usage: $0 { start | stop }"
        ;;
esac

# TODO: add status, try-restart, reload, force-reload

exit 0